module.exports = {
    commands: 'birdfact',
    expectedArgs: '',
    permissionError: "You don't have permission",
    minArgs: 0,
    maxArgs: 0,
    callback: (message) => {
        const facts = [
            "I learned about Peafowls by playing Zoo Tycoon",
            'There are 3 types of peacocks: Indian, Congo, and what was the other one again? Oh Green',
            'Around 2/3 of all bird species are found in tropical rainforests',
            'There are over 9500 species of birds',
            "Bird lungs are more efficient than human lungs",
            'Cats kill between 1.4 and 3.7 *billion* birds a year in just the US',
            'The kiwi is the only bird with nostrils at the end of its beak',
            'Woodpeckers drum their beaks against trees in place of singing',
            'The African Gray Parrot can say over 800 words compared to 50 for most others',
            'The Japanese Crested Iris is the rarest bird with less than 50 remaining in the world (aside from Kiara-senpai of course)',
            'Falconry started over 4000 years ago in Central Asia',
            'Coalminers often used canaries to detect poisonous levels of carbon monoxide gas. Miners knew that if the canary passed out they were in danger too. The phrase “Canary in a Coalmine” derives from this history',
            "A pelican's beak can hold up to 2.5 gallons of water",
            "The part of a bird's leg that bends backwards is actually it's ankle, the knee is higher up in the feathers",
            "Ostriches lay the biggest eggs in the world",
            "The Andean Condor is the largest bird of prey and can weigh up to 27 pounds (12 kg)",
            "Birds are believed to have evolved from dinosaurs during the Mesozoic Era about 150 million years ago",
            "Flamingos choose mates for life",
            "The Argentine Lake Duck is around 16 inches tall but it's [redacted] can extend up to 17 inches. Watch out Subaru-senpai",
            "Gentoo Penguins can swim to speeds up to 22 mph (36 kph)",
            "Arctic terns fly 25,000 miles (40,000 km) to migrate every year",
            "The Wandering albatross' wingspan can be up to almost 12 feet (3.63 m)",
            "The Griffon Vulture is the highest flying bird at 6.8 miles (11 km) high",
            "The European wren sings at around 700 notes per minute",
            "Ostriches are the largest/tallest/heaviest birds at 9 ft (2.7 m) tall and 350 pounds (160 kg)",
            "The biggest bird to ever exist was the Flightless Elephant Bird at 1000 pounds (450 kg)",
            "The Emperor Penguin lays it's eggs in the middle of winter so that it's chicks have all year to grow before the next winter",
            "The Peregrine Falcon can reach speeds of up to 110 mph (180 kph) during dives",
            "Oilbirds are the only birds that can use echolocation, but they aren't as good at it as bats. Bats are so adept at it that they can fly through a fan's moving blades",
            "Birds have 3 fingers on each wing",
            "Birds that perch have 4 toes, ground birds have 3, and ostriches have 2",
            "The Sooty Tern spends 3 years in the air without landing, it sleeps by spreading it's wings and gliding on air currents",
            "Wish bones are bird collarbones",
            "Crows are able to remember human faces and hold a grudge, and can even share this info with other crows",
            "A group of crows is called a murder or congress. A group of owls is called a parliament, wisdom, or study. A group of flamingos is called a flamboyance",
            "The Cassowary is the most dangerous bird in the world, able to kill with it's kick",
            "Birds raised for food are the largest source of protein for humans",
            "Birds are often associated with the journey of the soul after death or as mediators between the dead and living in many myths",
            "Angry Birds was developed by only 4 people",
            "The oldest known bird after Kiara-senpai is the Archaeopteryx",
            "Birds are the only animals with feathers",
            "The bald eagle is called bald because it is only black and white, also known as 'piebald'",
            "Eleven percent of the world’s bird species are endangered. Draining wetlands and felling forests are the main causes of damage, but pollution and pesticides also play a part",
            "Before 1840, there were thousands of millions of passenger pigeons in North America. However, they were slaughtered for food until only one was left, a female called Martha. She died when she was 12 years old in 1914, in a zoo in Ohio",
            'The word "swan" is derived from the Indo-European root *swen, meaning "to sound, to sing"',
            'Someone who suffers from "anatidaephobia" believes that somewhere, somehow a duck or goose is constantly watching them',
            'There are more fake flamingos on Earth than real ones',
            "The wedge-tailed eagle is the only eagle that can see better than humans despite the phrase 'eagle eyed' referring to having good sight",
            'The word "falcon" is from the Latin "falx," meaning "curved blade, pruning hook, sickle, war-scythe',
            'A flock of ravens is called an “unkindness” or a "conspiracy"',
            'About two-thirds of birds in North America are at risk of extinction due to climate change',
        ]
        factNumber = Math.floor(Math.random() * (facts.length) )
        //console.log(`${facts.length}`)
        message.channel.send(`${facts[factNumber]}!`)
        console.log(`${message.author.username} ran the command "birdfact" in channel #${message.channel.name}`)
    },
    permissions: [],
    requiredRoles: [''],
}